spring.application.name=optica-backend

spring.datasource.url=jdbc:postgresql://db.ianboqaanrgkhagzamkc.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=yrsolutions2026
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

